# Generated by Django 6.0.2 on 2026-03-03 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_announcement_expires_at_reminder_expires_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveStudentAssistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=8)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("course", models.CharField(blank=True, default="", max_length=100)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1st", "1st Semester"),
                            ("2nd", "2nd Semester"),
                            ("summer", "Summer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 2024-2025",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "required_hours",
                    models.PositiveIntegerField(
                        default=200, help_text="Total hours required for the semester."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_assistants",
                        to="home.office",
                    ),
                ),
                (
                    "new_application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sa",
                        to="home.newapplication",
                    ),
                ),
                (
                    "renewal_application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sa",
                        to="home.renewalapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Student Assistant",
                "verbose_name_plural": "Active Student Assistants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="home.activestudentassistant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "-time_in"],
                "unique_together": {("student_assistant", "date")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_period",
                    models.CharField(
                        choices=[
                            ("midterm", "Midterm"),
                            ("final", "Final / End-of-Term"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "work_quality",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Poor, 5 = Excellent"
                    ),
                ),
                (
                    "punctuality",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Poor, 5 = Excellent"
                    ),
                ),
                (
                    "initiative",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Poor, 5 = Excellent"
                    ),
                ),
                (
                    "cooperation",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Poor, 5 = Excellent"
                    ),
                ),
                (
                    "communication",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Poor, 5 = Excellent"
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="home.activestudentassistant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Evaluation",
                "verbose_name_plural": "Performance Evaluations",
                "ordering": ["-evaluated_at"],
                "unique_together": {("student_assistant", "evaluation_period")},
            },
        ),
    ]
