# Generated by Django 6.0.2 on 2026-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_activestudentassistant_attendancerecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activestudentassistant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=15,
            ),
        ),
    ]
