# Generated by Django 6.0.2 on 2026-03-06 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_newapplication_student_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="application_id",
        ),
        migrations.AddField(
            model_name="newapplication",
            name="gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="General weighted average (1.00–5.00 scale).",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="General weighted average (1.00–5.00 scale).",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewal_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(
                default="00000000",
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Student ID must be exactly 8 digits."
                    ),
                ],
            ),
        ),
        migrations.CreateModel(
            name="NoDutyDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        help_text="e.g. Holiday, Office Closed", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="no_duty_days_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to apply to ALL offices.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_duty_days",
                        to="home.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "No-Duty Day",
                "verbose_name_plural": "No-Duty Days",
                "ordering": ["-date"],
                "unique_together": {("date", "office")},
            },
        ),
    ]
