# Generated by Django 6.0.2 on 2026-03-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_add_returned_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationnote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("staff", "Staff Note"),
                    ("director", "Director Note"),
                    ("schedule_mismatch", "Schedule Mismatch"),
                    ("schedule_resubmit", "Schedule Resubmitted"),
                    ("document_request", "Document Request"),
                    ("document_return", "Document Returned"),
                    ("document_resubmit", "Documents Resubmitted"),
                    ("status_change", "Status Change"),
                ],
                default="staff",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DutyReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("shift", models.CharField(max_length=30)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming Shift"),
                            ("absent", "Absent Notification"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_reminders",
                        to="home.activestudentassistant",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("student_assistant", "date", "shift", "reminder_type")
                },
            },
        ),
    ]
