# Generated by Django 6.0.2 on 2026-03-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_add_duty_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="performanceevaluation",
            name="recommendation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Not Set —"),
                    ("rehire", "Recommend for Rehire"),
                    ("not_rehire", "Do Not Rehire"),
                    ("conditional", "Conditional Rehire"),
                ],
                default="",
                help_text="Rehire recommendation for contract renewal",
                max_length=15,
            ),
        ),
    ]
